In [14]:
from sklearn.svm import LinearSVC
from sklearn.datasets import make_classification
X, y = make_classification(n_features=4, random_state=0)
clf = LinearSVC(random_state=0, tol=1e-5)
clf.fit(X, y)

d = clf.decision_function(X)

print (X.shape)
print (d.shape)
d

(100, 4)
(100,)


array([ 0.5009639 ,  2.37030433, -0.71512462, -0.49748866, -0.83294182,
       -1.43521603, -1.8254493 ,  0.44234494, -0.45427349,  1.50913755,
       -0.71673523,  0.12179075,  1.09718729,  3.05546177,  0.00662194,
       -0.69658317, -0.60910527, -1.36849645,  0.05494463,  3.50312168,
        0.99672532, -0.38879602, -2.46652119,  0.92477227, -0.80856607,
       -1.12866745,  0.45167687,  0.95927493, -1.10228964, -0.05592487,
       -0.86361672,  1.93583299, -2.79995593,  0.85640546, -0.02745133,
        2.60383711, -0.60796053,  3.07413646, -3.40632503, -0.78003834,
        1.88125071,  1.13671223, -0.44741754, -0.77294834, -1.01345052,
        0.76705319, -1.17347129, -0.59680843,  1.7538333 , -1.06180788,
        2.78778645, -2.45464274, -0.82857817,  1.11672915, -0.25150956,
        3.10204245, -2.43804566, -0.47725696,  2.24067516,  1.8308251 ,
       -0.90045788, -0.52137567, -0.59864317, -0.90196074,  1.39798863,
        4.97678164,  0.63547127,  0.72217439,  0.96454723, -0.30

In [13]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
b = lb.fit_transform([1, 2, 6, 4, 2])
print(lb.classes_)
print (b)

[1 2 4 6]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


In [34]:
import numpy as np

a = np.array([[1, 5, 3], [0, 1, 2], [10, 9, 8], [20, 19, 18]])
np.argmax(a, axis=1)

array([1, 2, 0, 0])