In [17]:
import numpy as np

nclasses = 3
y = 2
x = np.array([1, 2, 3, 4])
s = 4
z = np.zeros(s)

#np.concatenate((z, x, z), axis=0)
t = x

for i in range(0, y):
    t = np.concatenate((z, t), axis=0)
for i in range(0, nclasses - y -1):
    t = np.concatenate((t, z), axis=0)
    
x = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
x[1] = np.array([0, 0, 0])
print (x)

[[1 1 1]
 [0 0 0]
 [3 3 3]
 [4 4 4]]
